poetry/apps/accounts/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from accounts.views import SignUpView, CheckUniqueView

urlpatterns = [
    url(r'^signup/$', SignUpView.as_view(), name='signup'),
    url(r'^login/$', auth_views.login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^check_unique/$', CheckUniqueView.as_view(), name='check_unique'),
]

poetry/apps/api/urls.py
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns

from poetry.apps.api.views import GetAccent

urlpatterns = [
    url(r'^accent/', GetAccent.as_view()),
]

poetry/apps/corpus/urls.py
from django.conf.urls import url, include

from poetry.apps.corpus.views.comparison_view import ComparisonView, ComparisonCSVView
from poetry.apps.corpus.views.poem_list_view import PoemsListView
from poetry.apps.corpus.views.markup_view import MarkupView, MarkupMakeStandardView, MarkupDeleteView
from poetry.apps.corpus.views.version_list_view import MarkupVersionListView
from poetry.apps.corpus.views.version_export_view import MarkupVersionExportView
from poetry.apps.corpus.views.poem_view import PoemView, PoemDeleteView, PoemMakeStandardView

urlpatterns = [
    url(r'^poem_list/', PoemsListView.as_view(), name='poems'),
    url(r'^versions/', MarkupVersionListView.as_view(), name='versions'),
    url(r'^export_version/(?P<pk>[0-9]*)/$', MarkupVersionExportView.as_view(), name='export_version'),
    url(r'^poems/(?P<pk>[0-9]*)/$', PoemView.as_view(), name="poem"),
    url(r'^poems/(?P<pk>[0-9]*)/make_standard$', PoemMakeStandardView.as_view(), name="poem_make_standard"),
    url(r'^poems/(?P<pk>[0-9]*)/delete$', PoemDeleteView.as_view(), name="poem_delete"),
    url(r'^markups/(?P<pk>[0-9]*)/$', MarkupView.as_view(), name="markup"),
    url(r'^markups/(?P<pk>[0-9]*)/delete$', MarkupDeleteView.as_view(), name="markup_delete"),
    url(r'^markups/(?P<pk>[0-9]*)/make_standard$', MarkupMakeStandardView.as_view(), name="markup_make_standard"),
    url(r'^search/', include('haystack.urls', namespace="search")),
    url(r'^comparison/$', ComparisonView.as_view(), name="comparison"),
    url(r'^comparison_csv/$', ComparisonCSVView.as_view(), name="comparison_csv"),
]

poetry/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap, index

from django.views.generic import TemplateView
from poetry.sitemaps import StaticViewSitemap
from poetry.apps.accounts.sitemaps import AccountsStaticSitemap
from poetry.apps.corpus.sitemaps import CorpusDataSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'accounts': AccountsStaticSitemap,
    'corpus': CorpusDataSitemap
}

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="about.html"), name='about'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^corpus/', include('corpus.urls', namespace='corpus')),
    url(r'^download/', TemplateView.as_view(template_name="download.html"), name='download'),
    url(r'^sitemap\.xml$', index, {'sitemaps': sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots\.txt', include('robots.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

poetry/apps/accounts/views.py
# -*- coding: utf-8 -*-

from django.views.generic.edit import FormView, View
from django.core.urlresolvers import reverse_lazy
from django.db import transaction
from django.http import JsonResponse
from django.contrib.auth import authenticate, login

from accounts.models import MyUser
from accounts.forms import SignUpForm


class SignUpView(FormView):
    """
    Страница регистрации пользователя. Пользователь создаётся НЕ активным, нужно подтверждение.
    Дополнительные действия - установка стандартной аватарки.
    """
    template_name = 'accounts/signup.html'
    form_class = SignUpForm
    success_url = reverse_lazy('about')

    def form_valid(self, form):
        form = form.cleaned_data
        user = MyUser.objects.create_user(email=form['email'], password=form['password'],
                                          first_name=form['first_name'], last_name=form['last_name'],
                                          organisation=form['organisation'])
        user.save()
        user = authenticate(email=form['email'], password=form['password'])
        login(self.request, user)
        return super(SignUpView, self).form_valid(form)


class CheckUniqueView(View):
    """
    Действие для проверки уникальности логина и почты.
    Клиентская часть в signup.js, функции check_username и check_email.
    """
    def get(self, request, *args, **kwargs):
        email = request.GET['email']
        result = {'email': '0'}
        if email != '':
            if MyUser.objects.all().filter(email=email).exists():
                result['email'] = '1'
        return JsonResponse(result, status=200)

poetry/apps/api/views.py
from rest_framework.views import APIView


class GetAccent(APIView):
    def get(self, request, format=None):
        raise NotImplementedError()

poetry/apps/corpus/views.py
from rest_framework import viewsets
from poetry.apps.corpus.serializers import PoemSerializer, MarkupVersionSerializer, MarkupSerializer
from poetry.apps.corpus.models import Poem, MarkupVersion, Markup


class PoemViewSet(viewsets.ModelViewSet):
    queryset = Poem.objects.all()
    serializer_class = PoemSerializer


class MarkupVersionViewSet(viewsets.ModelViewSet):
    queryset = MarkupVersion.objects.all()
    serializer_class = MarkupVersionSerializer


class MarkupViewSet(viewsets.ModelViewSet):
    queryset = Markup.objects.all()
    serializer_class = MarkupSerializer

poetry/apps/corpus/views/comparison_view.py
from collections import namedtuple
from typing import List

from django.views.generic import TemplateView, View
from django.http import HttpResponse
from braces.views import LoginRequiredMixin, GroupRequiredMixin

from poetry.apps.corpus.models import Poem, MarkupVersion
from rupo.main.markup import Markup


def get_accents(markup: Markup):
    accents = []
    for line in markup.lines:
        for word in line.words:
            for syllable in word.syllables:
                accents.append(syllable.stress != -1)
    return accents


def get_accuracy(standard_accents: List[bool], test_accents: List[bool]):
    l = min(len(standard_accents), len(test_accents))
    hits = sum([1 for standard_accent, test_accent in zip(standard_accents, test_accents)
                if standard_accent == test_accent])
    return float(hits) / l


def get_precision(standard_accents: List[bool], test_accents: List[bool]):
    tp = sum([1 for standard_accent, test_accent in zip(standard_accents, test_accents)
              if standard_accent == test_accent == 1])
    tp_fp = sum([1 for accent in test_accents if accent == 1])
    return float(tp) / tp_fp


def get_recall(standard_accents: List[bool], test_accents: List[bool]):
    tp = sum([1 for standard_accent, test_accent in zip(standard_accents, test_accents)
              if standard_accent == test_accent == 1])
    tp_fn = sum([1 for accent in standard_accents if accent == 1])
    return float(tp) / tp_fn


def get_comparison(poem, standard_pk, test_pk):
    test_markup = None
    standard_markup = None
    for markup in poem.markups.all():
        if markup.markup_version.pk == standard_pk:
            standard_markup = markup
        if markup.markup_version.pk == test_pk:
            test_markup = markup
    assert test_markup.get_markup().text == standard_markup.get_markup().text
    standard_accents = get_accents(standard_markup.get_markup())
    test_accents = get_accents(test_markup.get_markup())
    accuracy = get_accuracy(standard_accents, test_accents)
    precision = get_precision(standard_accents, test_accents)
    recall = get_recall(standard_accents, test_accents)
    f1 = 2*precision*recall/(precision+recall)
    Comparison = namedtuple("Comparison", "poem test standard accuracy precision recall f1")
    return Comparison(poem=poem, test=test_markup, standard=standard_markup, accuracy=accuracy,
                      precision=precision, recall=recall, f1=f1)


def get_all_comparisons(standard_pk, test_pk):
    standard_markup_version = MarkupVersion.objects.get(pk=standard_pk)
    poems = list(set([markup.poem for markup in standard_markup_version.markups.filter(
        poem__markups__markup_version=test_pk)]))
    return [get_comparison(poem, standard_pk, test_pk) for poem in poems]


class ComparisonView(LoginRequiredMixin, GroupRequiredMixin, TemplateView):
    template_name = 'comparison.html'
    group_required = "Approved"

    def get_context_data(self, **kwargs):
        context = super(ComparisonView, self).get_context_data(**kwargs)
        test_pk = int(self.request.GET["test"])
        standard_pk = int(self.request.GET["standard"])
        document_pk = self.request.GET.get("document", None)

        if document_pk is None:
            comparisons = get_all_comparisons(standard_pk, test_pk)
        else:
            comparisons = [get_comparison(Poem.objects.get(pk=document_pk), standard_pk, test_pk)]
        context["comparisons"] = comparisons
        context["avg_accuracy"] = sum([comparison.accuracy for comparison in comparisons])/len(comparisons)
        context["avg_f1"] = sum([comparison.f1 for comparison in comparisons]) / len(comparisons)
        return context


class ComparisonCSVView(LoginRequiredMixin, GroupRequiredMixin, View):
    group_required = "Approved"

    def get(self, request, *args, **kwargs):
        standard_pk = int(request.GET["standard"])
        test_pk = int(request.GET["test"])
        response = HttpResponse()
        comparisons = get_all_comparisons(standard_pk, test_pk)
        content = "poem,test,standard,accuracy,precision,recall,f1\n"
        for comparison in comparisons:
            content += ",".join([comparison.poem.name.replace(",", ""),
                                 comparison.test.author.replace(",", ""),
                                 comparison.standard.author.replace(",", ""),
                                 "{:.3f}".format(comparison.accuracy),
                                 "{:.3f}".format(comparison.precision),
                                 "{:.3f}".format(comparison.recall),
                                 "{:.3f}".format(comparison.f1)]) + "\n"
        response.content = content
        response["Content-Disposition"] = "attachment; filename={0}".format(
            "comparison" + str(standard_pk) + "-" + str(test_pk) + ".csv")
        return response

poetry/apps/corpus/views/markup_view.py
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import JsonResponse
from django.views.generic import DetailView, View, DeleteView
from django.views.generic.detail import SingleObjectMixin

from braces.views import LoginRequiredMixin, GroupRequiredMixin

from poetry.apps.corpus.models import Markup, MarkupVersion
from rupo.main.markup import Markup as TextMarkup
from rupo.util.preprocess import VOWELS


def process_markup(markup):
    text = markup.text
    output = []
    prev = 0
    for l in range(len(markup.lines)):
        line = markup.lines[l]
        output.append([])
        for w in range(len(line.words)):
            word = line.words[w]
            t = text[prev:word.begin]
            output[-1].append({'word': {'text': t}, 'word_number': -1})
            if len(word.syllables) == 0:
                output[-1].append({'word': {'text': word.text}, 'word_number': w})
            else:
                output[-1].append({'word': {'text': word.text, 'syllables': []}, 'word_number': w})
                accents_count = sum([1 for syllable in word.syllables if syllable.stress != -1])
                for s in range(len(word.syllables)):
                    syllable = word.syllables[s]
                    output[-1][-1]['word']['syllables'].append(
                        {'text': syllable.text, 'stress': syllable.stress,
                         'omography': accents_count > 1, 'no_accent': accents_count == 0})
            prev = word.end
        output[-1].append({'word': {'text': text[prev:line.end]}, 'word_number': -1})
        prev = line.end
    return output


class MarkupView(DetailView):
    model = Markup
    template_name = 'markup.html'
    context_object_name = 'markup'

    def get_context_data(self, **kwargs):
        context = super(MarkupView, self).get_context_data(**kwargs)
        markup = self.get_object()
        m = TextMarkup()
        m.from_json(markup.data)
        context['text'] = process_markup(m)
        context['poem'] = markup.poem
        context['poem'].name = markup.poem.get_name()
        context['lines_count'] = markup.poem.count_lines()
        context['additional'] = markup.get_automatic_additional()
        markups = set()
        for markup_instance in markup.poem.markups.all():
            markups.add(markup_instance.markup_version)
        context['markups'] = list(markups)
        return context

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            diffs = request.POST.getlist('diffs[]')

            m = self.get_object()
            poem = m.poem
            markup = m.get_markup()

            for diff in diffs:
                l = int(diff.split('-')[0])
                w = int(diff.split('-')[1])
                s = int(diff.split('-')[2])
                syllable = markup.lines[l].words[w].syllables[s]
                if syllable.stress != -1:
                    syllable.stress = -1
                else:
                    for i in range(len(syllable.text)):
                        if syllable.text[i] in VOWELS:
                            syllable.stress = syllable.begin + i

            m = Markup()
            if Markup.objects.filter(author=request.user.email, poem=poem).exists():
                m = Markup.objects.filter(author=request.user.email, poem=poem)[0]
            m.text = markup.to_json()
            m.author = request.user.email
            m.poem = poem
            m.markup_version = MarkupVersion.objects.get(name="Manual")
            m.save()
            return JsonResponse({'url': reverse('corpus:markup', kwargs={'pk': m.pk}),}, status=200)
        else:
            raise PermissionDenied


class MarkupMakeStandardView(LoginRequiredMixin, GroupRequiredMixin, View, SingleObjectMixin):
    model = Markup
    group_required = "Approved"
    raise_exception = True

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated() and request.user.is_superuser:
            markup = self.get_object()
            if not MarkupVersion.objects.filter(name="Standard").exists():
                MarkupVersion.objects.create(name="Standard", is_manual=True)
            standard_version = MarkupVersion.objects.get(name="Standard")
            markup.is_standard = True
            markup.markup_version = standard_version
            markup.save()
            return JsonResponse({'url': reverse('corpus:markup', kwargs={'pk': markup.pk}), }, status=200)
        else:
            raise PermissionDenied


class MarkupDeleteView(LoginRequiredMixin, GroupRequiredMixin, DeleteView):
    model = Markup
    group_required = "Approved"
    success_url = reverse_lazy('corpus:poems')
    raise_exception = True

poetry/apps/corpus/views/poem_list_view.py
from django.views.generic import ListView

from poetry.apps.corpus.models import Poem


class PoemsListView(ListView):
    model = Poem
    template_name = 'poems.html'
    context_object_name = 'poems'
    paginate_by = 50

    def get_context_data(self, **kwargs):
        context = super(PoemsListView, self).get_context_data(**kwargs)
        poems_list = []
        for poem in context['poems']:
            if not self.request.user.has_perm('corpus.can_view_restricted_poems') and poem.is_restricted:
                continue
            poem.name = poem.get_name()
            poems_list.append(poem)
        return context

poetry/apps/corpus/views/version_export_view.py
from django.views.generic.detail import SingleObjectMixin
from django.views.generic import View
from django.http import HttpResponse
from braces.views import LoginRequiredMixin, GroupRequiredMixin

from poetry.apps.corpus.models import MarkupVersion


class MarkupVersionExportView(LoginRequiredMixin, GroupRequiredMixin, SingleObjectMixin, View):
    model = MarkupVersion
    group_required = "Approved"

    def get(self, request, *args, **kwargs):
        version = self.get_object()
        response = HttpResponse()
        content = "["
        for markup in version.markups.all():
            content += markup.text + ","
        content = content[:-1] + "]"
        response.content = content
        response["Content-Disposition"] = "attachment; filename={0}".format(version.name + ".json")
        return response

poetry/apps/corpus/views/version_list_view.py
from django.views.generic import ListView
from braces.views import LoginRequiredMixin, GroupRequiredMixin

from poetry.apps.corpus.models import MarkupVersion


class MarkupVersionListView(LoginRequiredMixin, GroupRequiredMixin, ListView):
    model = MarkupVersion
    template_name = 'versions.html'
    context_object_name = 'versions'
    paginate_by = 50
    group_required = "Approved"

poetry/templates/about.html
{% extends "base.html" %}

{% block about_active %} class="active" {% endblock %}
{% block content %}
<div class="page-header">
    <h3>О проекте</h3>
</div>
<div class="row">
    <div class="col-lg-12">
        <p>Этот сайт - корпус стихотворений русских поэтов 19-20 веков, размеченных по слогам и ударениям.</p>
        <p>Кроме того, реализован генератор стихотворений на основе марковских цепей.</p>
        <p>Исходный код разметчика и генератора в находится открытом доступе.</p>
        <p>Характеристики:</p>
        <ul>
            <li>Символов: 13208090</li>
            <li>Слов: 2186827</li>
            <li>Стихотворений: 16694</li>
            <li>Стихотворений, протегированных темами: 3904</li>
            <li>Авторов: 195</li>
        </ul>
    </div>
</div>
{% endblock %}

poetry/templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Поэтический корпус</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <link rel="stylesheet" href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'css/typographic.css' %}">
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    <link rel="shortcut icon" href="{% static 'img/favicon/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'img/favicon/favicon.ico' %}" type="image/x-icon">

    <script src="{% static 'lib/jquery/js/jquery.min.js' %}"></script>
    <script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/ajax.csrf.js' %}"></script>
    <script src="{% static 'js/common.js' %}"></script>
    {% block custom_head %}
    {% endblock %}
    <meta name="google-site-verification" content="QiUuvkUHh60lYdlPcFhQfamELL-EhJ5CF6TDeZskQB0" />
    <meta name="yandex-verification" content="b7e672a8b3f45305" />
</head>
<body style="padding-top:50px;">
<div id="wrap">
    <nav class = "navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Poetry corpus</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li {% block about_active %} {% endblock %}>
                        <a href="{% url 'about' %}">О проекте</a>
                    </li>
                    <li {% block poems_active %} {% endblock %}>
                        <a href="{% url 'corpus:poems' %}?page=1">Корпус</a>
                    </li>
                    <li {% block versions_active %} {% endblock %}>
                        <a href="{% url 'corpus:versions' %}?page=1">Версии разметок</a>
                    </li>
                    <li {% block search_active %} {% endblock %}>
                        <a href="{% url 'corpus:search:haystack_search' %}">Поиск</a>
                    </li>
                </ul>
                <ul class = "nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a>{{user.email}}</a></li>
                    <li><a href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out"></i> Выйти</a><li>
                {% else %}
                     <li {% block signup_active %} {% endblock %}><a href="{% url 'accounts:signup' %}"><i class="fa fa-edit"></i>  Регистрация</a></li>
                    <li {% block login_active %} {% endblock %}><a href="{% url 'accounts:login' %}"><i class="fa fa-sign-in"></i>  Вход</a></li>
                {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <div id="push"></div>
</div>

<div id="footer">
    <div class="container">
        <div class="text-muted credit text-center">
            <p>Гусев Илья, 2016.</p>
            <a href="https://github.com/IlyaGusev/PoetryCorpus">Исходный код</a>,
            <a href="https://github.com/IlyaGusev/PoetryCorpus">правила использования</a>.
        </div>
    </div>
</div>
</body>
</html>

poetry/templates/download.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block download_active %} class="active" {% endblock %}
{% block content %}
<div class="page-header">
    <h3>Скачать корпус</h3>
</div>
<div class="row">
    <div class="col-large-12">
        <p>Скачать <a href="{% static 'download/TextsMeta.zip' %}">TextMeta.zip</a> - стихотворения с метаданными, 8 MB</p>
        <p>Скачать <a href="{% static 'download/Markups.zip' %}">Markups.zip</a> - разметки, 68 MB</p>
        <p>Скачать <a href="{% url 'corpus:download' %}">ручные разметки</a></p>
    </div>
</div>
{% endblock %}

poetry/templates/markup.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block custom_head %}
<script src="{% static 'js/ajax.csrf.js' %}"></script>
<script src="{% static 'lib/mousetrap/mousetrap.min.js' %}"></script>
<script src="{% static 'js/markup.js' %}"></script>
{% endblock %}
{% block content %}
<div class="page-header">
    <h3>{{ poem.author }} - {{ poem.name }}</h3>
</div>
<div class="col-lg-6">
    <select class="form-control markup-selector">
        {% for markup in poem.markups.all %}
            <option value="{{markup.pk}}" class="markup">{{ markup.author}}</option>
        {% endfor %}
    </select>
</div>
<div style="font-size: 20px; padding-top: 20px;" class="col-lg-9 poem" id="{{ poem.pk }}">
<p style="font-size: 15px;">Кликайте по слогами, чтобы менять ударение</p>
{% include "accented.html" with text=text %}


<div style="padding-top:20px;">
    {% if user.is_authenticated %}
    <button class="btn btn-md btn-warning send-markup">Сохранить разметку</button>
    {% endif %}
    {% if user.is_authenticated and user.is_superuser and markup.markup_version.is_manual %}
        <a class="btn btn-md btn-danger delete-view" href="{% url 'corpus:markup_delete' pk=markup.pk %}" id="delete-button">Удалить</a>
    {% endif %}
    {% if user.is_authenticated and user.is_superuser and markup.markup_version.is_manual and not markup.is_standard %}
        <a class="btn btn-md btn-success" href="{% url 'corpus:markup_make_standard' pk=markup.pk %}" id="markup-make-standard">Пометить как эталонную</a>
    {% endif %}
    {% if not user.is_authenticated  %}
    <p style="font-size: 15px;">Только авторизованные пользователи могут добавлять разметку.</p>
    {% endif %}
</div>

<div style="padding-top:20px;">
    <a class="btn btn-md btn-primary" href="{% url 'corpus:poem' pk=poem.pk %}" id="to-text-button">Назад к тексту</a>
</div>
</div>

<div class="col-lg-3">
    <h4>Доп. информация</h4>
    <p>Строк: {{lines_count}}</p>
    {{ markup.get_automatic_additional|linebreaksbr }}
     {% for rhyme in rhymes %}
        <p>{{rhyme}}</p>
    {% endfor %}
    <h4>Сравнение: </h4>
    Тестовая:
    <select class="form-control test">
        {% for markup in markups %}
            <option value="{{markup.pk}}" class="test">{{ markup.name}}</option>
        {% endfor %}
    </select>
    Эталонная
    <select class="form-control standard">
        {% for markup in markups %}
            <option value="{{markup.pk}}" class="standard">{{ markup.name}}</option>
        {% endfor %}
    </select>
    <div style="padding-top:10px;" class="text-center">
        <button class="btn btn-md btn-default compare">Сравнить</button>
    </div>
</div>
<div hidden id="poem_pk">{{poem.pk}}</div>

{% csrf_token %}
{% endblock %}

poetry/templates/poem.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block analysis_active %} class="active" {% endblock %}
{% block custom_head %}
    <script src="{% static 'lib/mousetrap/mousetrap.min.js' %}"></script>
    <script src="{% static 'js/poem.js' %}"></script>
{% endblock %}
{% block content %}
<div class="page-header">
    <h3 class="poem-name">
        {% if can_edit %}
        <span id="author">
            {{ poem.author }}
            <a href="#" class="light"><i class="fa fa-pencil" id="author-pencil"></i></a>
        </span>
        <span id="author-edit" class="hidden">
            <input id="author-field" type="text" value="{{ poem.author }}"/>
        </span>
            -
        <span id="name">
            {{ poem.name }}
            <a href="#" class="light"><i class="fa fa-pencil" id="name-pencil"></i></a>
        </span>
         <span id="name-edit" class="hidden">
            <input id="name-field" type="text" value="{{ poem.name }}"/>
        </span>
        {% else %}
        {{ poem.author }} - {{ poem.name }}</h3>
        {% endif %}
    </h3>
</div>
<div class="row" >
    {%  if poem.markups.all|length != 0 %}
    <a class="btn btn-md btn-primary" href="{% url 'corpus:markup' pk=poem.markups.all.0.pk %}" id="to-markups-button">Перейти к разметкам</a>
    {%  endif  %}
    {% if can_edit %}
    <a class="btn btn-md btn-warning" id="edit-button">Редактировать</a>
    <a class="btn btn-md btn-danger delete-view" id="delete-button" href="{% url 'corpus:poem_delete' poem.pk %}">Удалить</a>
    {% if not poem.is_standard %}
        <a class="btn btn-md btn-success" href="{% url 'corpus:poem_make_standard' pk=poem.pk %}" id="poem-make-standard">Пометить как проверенное</a>
    {% endif %}
    {% endif %}
</div>
<div class="row" style="padding-top:20px;">
    <div class="col-lg-12 bigger-letters plain-text">
        {{ poem.text|linebreaksbr }}
    </div>
    {% if can_edit %}
    <div class="col-lg-6 bigger-letters edit-plain-text hidden">
        <form>
            <textarea class="form-control mousetrap" rows="30" id="edit-text-field" name="text" style="overflow:auto;resize:none">{{ poem.text}}</textarea>
            <div style="padding-top:20px;">
                <button class="btn btn-md btn-success" type="submit" id="save-button">Сохранить</button>
                <button class="btn btn-md btn-danger" id="cancel-button">Отмена</button>
            </div>
        </form>
    </div>
    {% endif %}
</div>
<div class="row" style="padding-top:20px; padding-bottom: 20px;">
    <a class="btn btn-md btn-primary" href="{% url 'corpus:poem' pk=prev_pk %}" id="prev-button">Предыдущее</a>
    <a class="btn btn-md btn-primary" href="{% url 'corpus:poem' pk=next_pk %}" id="next-button">Следующее</a>
</div>

{% csrf_token %}
{% endblock %}